apiVersion: v1
kind: ConfigMap
metadata:
  name: efs-data-prep-map
data:
  S3_BUCKET: s3://wandb-finbert/
  MOUNT_PATH: /shared-efs

---
apiVersion: v1
kind: Pod
metadata:
  name: efs-data-prep-pod
spec:
  containers:
  - name: efs-data-prep-pod
    image: <registry>/s3-efs
    envFrom:
    - configMapRef:
        name: efs-data-prep-map
    command: ["/bin/bash"]
    args: ["-c", "/data-prep.sh"]
    volumeMounts:
    - name: efs-pvc
      mountPath: /shared-efs
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs-claim
  restartPolicy: Never
